<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>812e83a8-4c87-4799-beb4-f89a9043c78f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
	  <PackageReference Include="Scalar.AspNetCore" Version="2.16.18" />
	  <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.1" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5" />
	  <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TalentHub.Application\TalentHub.Application.csproj" />
    <ProjectReference Include="..\TalentHub.Infrastructure\TalentHub.Infrastructure.csproj" />
  </ItemGroup>

</Project>
